import { YearData, MonthData, WeekData } from '../types';
import { MONTH_NAMES } from '../constants';

const parseNumber = (val: string | undefined): number => {
  if (!val) return 0;
  const clean = val.trim();
  const num = parseFloat(clean);
  return isNaN(num) ? 0 : num;
};

export const parseCSVData = (csvContent: string): YearData[] => {
  const lines = csvContent.split('\n');
  const yearsData: YearData[] = [];
  const yearRowIndex = 2; 
  if (lines.length <= yearRowIndex) return [];

  const yearRow = lines[yearRowIndex].split(',');
  const yearIndices: { year: number; colIndex: number }[] = [];
  
  yearRow.forEach((cell, idx) => {
    const cleanCell = cell.trim();
    if (cleanCell && !isNaN(parseFloat(cleanCell))) {
      const year = Math.floor(parseFloat(cleanCell));
      if (year >= 2000 && year < 2100) {
        yearIndices.push({ year, colIndex: idx });
      }
    }
  });

  yearIndices.sort((a, b) => b.year - a.year);
  const monthStartRow = 3;
  const monthEndRow = 14;

  yearIndices.forEach(({ year, colIndex }) => {
    const months: MonthData[] = [];
    let yearTotal = 0;

    for (let i = monthStartRow; i <= monthEndRow; i++) {
      if (!lines[i]) continue;
      const row = lines[i].split(',');
      const monthName = MONTH_NAMES[i - monthStartRow];
      const monthlyTotal = parseNumber(row[colIndex]);
      const weeks: WeekData[] = [];

      for (let w = 1; w <= 5; w++) {
        let weekVal = parseNumber(row[colIndex + w]);
        if (weekVal > 500) weekVal = 0; 
        weeks.push({ weekNum: w, value: weekVal });
      }

      const calculatedTotal = weeks.reduce((sum, w) => sum + w.value, 0);
      const finalTotal = calculatedTotal > 0 ? calculatedTotal : monthlyTotal;

      months.push({
        name: monthName,
        total: parseFloat(finalTotal.toFixed(2)),
        weeks
      });
      yearTotal += finalTotal;
    }

    yearsData.push({
      year,
      months,
      total: parseFloat(yearTotal.toFixed(2))
    });
  });

  return yearsData;
};

export const exportToCSV = (yearsData: YearData[]): string => {
  let csv = "Generated by Master Paleo Analytics,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n";
  csv += ",,,"; 
  yearsData.forEach(() => {
    csv += "Total,Semana 1,Semana 2,Semana 3,Semana 4,Semana 5,,";
  });
  csv += "\n";
  csv += ",,,";
  yearsData.forEach(y => {
    csv += `${y.year},,,,,,,`;
  });
  csv += "\n";

  MONTH_NAMES.forEach((month, mIdx) => {
    csv += `${month},,,`; 
    yearsData.forEach(y => {
      const mData = y.months[mIdx];
      const val = (v: number) => (v === undefined || v === null || isNaN(v)) ? 0 : v;
      csv += `${val(mData.total)},${val(mData.weeks[0].value)},${val(mData.weeks[1].value)},${val(mData.weeks[2].value)},${val(mData.weeks[3].value)},${val(mData.weeks[4].value)},,`;
    });
    csv += "\n";
  });
  return csv;
};

// --- FUNCIONES DE RITMO (AUTOSUFICIENTES) ---

export const getDayOfYear = (): number => {
  const now = new Date();
  const start = new Date(now.getFullYear(), 0, 0);
  const diff = (now.getTime() - start.getTime()) + ((start.getTimezoneOffset() - now.getTimezoneOffset()) * 60 * 1000);
  const oneDay = 1000 * 60 * 60 * 24;
  return Math.floor(diff / oneDay);
};

export const calculatePace = (currentTotal: number) => {
  const dayOfYear = getDayOfYear();
  // Si estamos a 1 de enero, evitamos el infinito
  const safeDay = dayOfYear < 1 ? 1 : dayOfYear;
  
  const dailyPace = currentTotal / safeDay;
  
  return {
    daily: dailyPace,
    weekly: dailyPace * 7,
    monthly: dailyPace * 30.4375
  };
};
