import { YearData, MonthData, WeekData } from '../types';
import { MONTH_NAMES } from '../constants';

const parseNumber = (val: string | undefined): number => {
  if (!val) return 0;
  // Remove commas if european format, but here user has dots for decimals.
  const clean = val.trim();
  const num = parseFloat(clean);
  return isNaN(num) ? 0 : num;
};

export const parseCSVData = (csvContent: string): YearData[] => {
  const lines = csvContent.split('\n');
  const yearsData: YearData[] = [];

  // Find the row with years. In the provided file, it looks like row index 2 (line 3).
  // "empty, empty, empty, 2025, empty, empty, empty, empty, empty, 2024..."
  
  const yearRowIndex = 2; 
  if (lines.length <= yearRowIndex) return [];

  const yearRow = lines[yearRowIndex].split(',');

  // Identify column indices for each year
  // Pattern: Years are separated by 6 or 7 columns usually.
  
  const yearIndices: { year: number; colIndex: number }[] = [];
  
  yearRow.forEach((cell, idx) => {
    const cleanCell = cell.trim();
    if (cleanCell && !isNaN(parseFloat(cleanCell))) {
      // 2020.0 might be parsed as 2020
      const year = Math.floor(parseFloat(cleanCell));
      if (year >= 2000 && year < 2100) {
        yearIndices.push({ year, colIndex: idx });
      }
    }
  });

  // Sort by year descending just in case
  yearIndices.sort((a, b) => b.year - a.year);

  const monthStartRow = 3;
  const monthEndRow = 14;

  yearIndices.forEach(({ year, colIndex }) => {
    const months: MonthData[] = [];
    let yearTotal = 0;

    for (let i = monthStartRow; i <= monthEndRow; i++) {
      if (!lines[i]) continue;
      const row = lines[i].split(',');
      const monthName = MONTH_NAMES[i - monthStartRow];

      const monthlyTotal = parseNumber(row[colIndex]);
      const weeks: WeekData[] = [];

      for (let w = 1; w <= 5; w++) {
        let weekVal = parseNumber(row[colIndex + w]);
        
        // SANITY CHECK: 
        if (weekVal > 500) {
          weekVal = 0; 
        }

        weeks.push({ weekNum: w, value: weekVal });
      }

      // Re-calculate total from weeks to ensure consistency
      const calculatedTotal = weeks.reduce((sum, w) => sum + w.value, 0);

      // If weeks are empty but total exists (legacy data), take total.
      const finalTotal = calculatedTotal > 0 ? calculatedTotal : monthlyTotal;

      months.push({
        name: monthName,
        total: parseFloat(finalTotal.toFixed(2)),
        weeks
      });

      yearTotal += finalTotal;
    }

    yearsData.push({
      year,
      months,
      total: parseFloat(yearTotal.toFixed(2))
    });
  });

  return yearsData;
};

export const exportToCSV = (yearsData: YearData[]): string => {
  let csv = "Generated by Master Paleo Analytics,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n";
  
  // Row 2: Weeks header
  csv += ",,,"; 
  yearsData.forEach(() => {
    csv += "Total,Semana 1,Semana 2,Semana 3,Semana 4,Semana 5,,";
  });
  csv += "\n";

  // Row 3: Years
  csv += ",,,";
  yearsData.forEach(y => {
    csv += `${y.year},,,,,,,`;
  });
  csv += "\n";

  // Data Rows
  MONTH_NAMES.forEach((month, mIdx) => {
    csv += `${month},,,`; 
    yearsData.forEach(y => {
      const mData = y.months[mIdx];
      const val = (v: number) => (v === undefined || v === null || isNaN(v)) ? 0 : v;
      
      csv += `${val(mData.total)},${val(mData.weeks[0].value)},${val(mData.weeks[1].value)},${val(mData.weeks[2].value)},${val(mData.weeks[3].value)},${val(mData.weeks[4].value)},,`;
    });
    csv += "\n";
  });

  return csv;
};

// --- NUEVAS FUNCIONES PARA CÁLCULO DE RITMO (MASTER PALEO PRO) ---

// Devuelve el número de día del año actual (1 - 366)
export const getDayOfYear = (): number => {
  const now = new Date();
  const start = new Date(now.getFullYear(), 0, 0);
  const diff = now.getTime() - start.getTime();
  const oneDay = 1000 * 60 * 60 * 24;
  return Math.floor(diff / oneDay);
};

// Calcula el ritmo actual proyectado basado en lo que llevamos de año
export const calculatePace = (currentTotal: number) => {
  const dayOfYear = getDayOfYear();
  // Evitar división por cero o resultados extraños el 1 de enero
  if (dayOfYear < 1) return { daily: 0, weekly: 0, monthly: 0 };
  
  const dailyPace = currentTotal / dayOfYear;
  
  return {
    daily: dailyPace,
    weekly: dailyPace * 7,
    monthly: dailyPace * 30.4375 // Media de días por mes exacta (365.25 / 12)
  };
};
